In [11]:
import pandas as pd

df = pd.read_csv(r'F:\Project\E-commerce Sales Analytics\Data\raw\Superstore_Dataset.csv')

In [12]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [35]:
df["Product Name"] = (df["Product Name"].str.slice(0, 35).where(df["Product Name"].str.len() <= 35,df["Product Name"].str.slice(0, 35) + "..."))

In [36]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,Hon Deluxe Fabric Upholstered Stack...,731.9400
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Ty...,14.6200
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectang...,957.5775
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [31]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y', errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y', errors='coerce')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(13)
memory usage: 1.3+ MB

In [34]:
df.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
count,9800.000000,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9789.000000,9800,9800,9800,9800,9800,9800.000000
unique,NaN,4922,NaN,NaN,4,793,793,3,1,529,49,NaN,4,1861,3,17,1849,NaN
top,NaN,CA-2018-100111,NaN,NaN,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN
freq,NaN,14,NaN,NaN,5859,35,35,5101,9800,891,1946,NaN,3140,19,5909,1492,47,NaN
mean,4900.500000,NaN,2017-05-01 05:13:51.673469440,2017-05-05 04:17:52.653061120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55273.322403,NaN,NaN,NaN,NaN,NaN,230.769059
min,1.000000,NaN,2015-01-03 00:00:00,2015-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1040.000000,NaN,NaN,NaN,NaN,NaN,0.444000
25%,2450.750000,NaN,2016-05-24 00:00:00,2016-05-27 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23223.000000,NaN,NaN,NaN,NaN,NaN,17.248000
50%,4900.500000,NaN,2017-06-26 00:00:00,2017-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58103.000000,NaN,NaN,NaN,NaN,NaN,54.490000
75%,7350.250000,NaN,2018-05-15 00:00:00,2018-05-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90008.000000,NaN,NaN,NaN,NaN,NaN,210.605000
max,9800.000000,NaN,2018-12-30 00:00:00,2019-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99301.000000,NaN,NaN,NaN,NaN,NaN,22638.480000
std,2829.160653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32041.223413,NaN,NaN,NaN,NaN,NaN,626.651875

In [37]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [39]:
df[df['Postal Code'].isnull()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2234,2235,CA-2018-104066,2018-12-05,2018-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Head...,205.03
5274,5275,CA-2016-162887,2016-11-07,2016-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
8798,8799,US-2017-150140,2017-04-06,2017-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
9146,9147,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M7...,99.98
9147,9148,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
9148,9149,US-2017-165505,2017-01-23,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Ca...,1564.29
9386,9387,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
9387,9388,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
9388,9389,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
9389,9390,US-2018-127292,2018-01-19,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
9741,9742,CA-2016-117086,2016-11-08,2016-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,Riverside Palais Royal Lawyers Book...,4404.90

In [41]:
df["Postal Code"] = df["Postal Code"].fillna("05401")

In [42]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [43]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [45]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales'],
      dtype='object')

In [54]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()
df["quarter"] = df["order_date"].dt.quarter
df["shipping_days"] = (df["ship_date"] - df["order_date"]).dt.days

In [55]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales', 'order_year', 'order_month', 'month_name',
       'quarter', 'shipping_days'],
      dtype='object')

In [57]:
df[['order_year','order_month','month_name','quarter','shipping_days']].head(10)

   order_year  order_month month_name  quarter  shipping_days
0        2017           11   November        4              3
1        2017           11   November        4              3
2        2017            6       June        2              4
3        2016           10    October        4              7
4        2016           10    October        4              7
5        2015            6       June        2              5
6        2015            6       June        2              5
7        2015            6       June        2              5
8        2015            6       June        2              5
9        2015            6       June        2              5

In [59]:
df.to_csv(r"F:\Project\E-commerce Sales Analytics\Data\processed\superstore_cleaned.csv", index=False)

In [60]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (9.7.0)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
import pandas as pd
from sqlalchemy import create_engine, text

HOST = "localhost"
PORT = 3306
USER = "root"
PASSWORD = "tushar"      
DATABASE = "ecsales"

df = pd.read_csv(r"F:\Project\E-commerce Sales Analytics\Data\processed\superstore_cleaned.csv")

print("CSV Loaded Successfully")
print(df.head())

engine = create_engine(
    f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}"
)

with engine.connect() as conn:
    conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {DATABASE}"))
    conn.commit()

print(f"Database '{DATABASE}' is ready.")

engine = create_engine(
    f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

df.to_sql(
    name="superstore",
    con=engine,
    if_exists="replace",   
    index=False
)

print("Table created successfully.")
print("Data inserted successfully.")

query = "SELECT * FROM superstore LIMIT 10"

result = pd.read_sql(query, engine)

print("\nFirst 10 Records:")
print(result)

print("\nProcess Completed Successfully.")

CSV Loaded Successfully
   row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2017-152156  2017-11-08  2017-11-11    Second Class    CG-12520
1       2  CA-2017-152156  2017-11-08  2017-11-11    Second Class    CG-12520
2       3  CA-2017-138688  2017-06-12  2017-06-16    Second Class    DV-13045
3       4  US-2016-108966  2016-10-11  2016-10-18  Standard Class    SO-20335
4       5  US-2016-108966  2016-10-11  2016-10-18  Standard Class    SO-20335

     customer_name    segment        country             city  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

        product_id         category sub-category  \
0  FUR-BO-10001798        Furniture    Bookcases
1  FUR-CH-10000454        Furniture       Chairs
2  OFF-LA-10000240  Office Supplies       Labels
3  FUR-TA-10000577        Furniture       Tables
4  OFF-ST-10000760  Office Supplies      Storage

                             product_name     sales order_year order_month  \
0       Bush Somerset Collection Bookcase  261.9600       2017          11
1  Hon Deluxe Fabric Upholstered Stack...  731.9400       2017          11
2  Self-Adhesive Address Labels for Ty...   14.6200       2017           6
3  Bretford CR4500 Series Slim Rectang...  957.5775       2016          10
4          Eldon Fold 'N Roll Cart System   22.3680       2016          10

   month_name  quarter  shipping_days
0    November        4              3
1    November        4              3
2        June        2              4
3     October        4              7
4     October        4              7

[5 rows x 23 columns]
Database 'ecsales' is ready.
Table created successfully.
Data inserted successfully.

First 10 Records:
   row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2017-152156  2017-11-08  2017-11-11    Second Class    CG-12520
1       2  CA-2017-152156  2017-11-08  2017-11-11    Second Class    CG-12520
2       3  CA-2017-138688  2017-06-12  2017-06-16    Second Class    DV-13045
3       4  US-2016-108966  2016-10-11  2016-10-18  Standard Class    SO-20335
4       5  US-2016-108966  2016-10-11  2016-10-18  Standard Class    SO-20335
5       6  CA-2015-115812  2015-06-09  2015-06-14  Standard Class    BH-11710
6       7  CA-2015-115812  2015-06-09  2015-06-14  Standard Class    BH-11710
7       8  CA-2015-115812  2015-06-09  2015-06-14  Standard Class    BH-11710
8       9  CA-2015-115812  2015-06-09  2015-06-14  Standard Class    BH-11710
9      10  CA-2015-115812  2015-06-09  2015-06-14  Standard Class    BH-11710

     customer_name    segment        country             city  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
5  Brosina Hoffman   Consumer  United States      Los Angeles  ...
6  Brosina Hoffman   Consumer  United States      Los Angeles  ...
7  Brosina Hoffman   Consumer  United States      Los Angeles  ...
8  Brosina Hoffman   Consumer  United States      Los Angeles  ...
9  Brosina Hoffman   Consumer  United States      Los Angeles  ...

        product_id         category sub-category  \
0  FUR-BO-10001798        Furniture    Bookcases
1  FUR-CH-10000454        Furniture       Chairs
2  OFF-LA-10000240  Office Supplies       Labels
3  FUR-TA-10000577        Furniture       Tables
4  OFF-ST-10000760  Office Supplies      Storage
5  FUR-FU-10001487        Furniture  Furnishings
6  OFF-AR-10002833  Office Supplies          Art
7  TEC-PH-10002275       Technology       Phones
8  OFF-BI-10003910  Office Supplies      Binders
9  OFF-AP-10002892  Office Supplies   Appliances

                             product_name     sales order_year order_month  \
0       Bush Somerset Collection Bookcase  261.9600       2017          11
1  Hon Deluxe Fabric Upholstered Stack...  731.9400       2017          11
2  Self-Adhesive Address Labels for Ty...   14.6200       2017           6
3  Bretford CR4500 Series Slim Rectang...  957.5775       2016          10
4          Eldon Fold 'N Roll Cart System   22.3680       2016          10
5  Eldon Expressions Wood and Plastic ...   48.8600       2015           6
6                              Newell 322    7.2800       2015           6
7          Mitel 5320 IP Phone VoIP phone  907.1520       2015           6
8  DXL Angle-View Binders with Locking...   18.5040       2015           6
9        Belkin F5C206VTEL 6 Outlet Surge  114.9000       2015           6

   month_name  quarter  shipping_days
0    November        4              3
1    November        4              3
2        June        2              4
3     October        4              7
4     October        4              7
5        June        2              5
6        June        2              5
7        June        2              5
8        June        2              5
9        June        2              5

[10 rows x 23 columns]

Process Completed Successfully.